# Generated by Django 2.2.3 on 2019-07-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufactures', '0002_auto_20190727_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='state',
            field=models.CharField(choices=[('preparation', 'Para preparar'), ('cut', 'Cortados'), ('sewing', 'En costura')], default='preparation', max_length=50),
        ),
    ]
