# Generated by Django 2.2.3 on 2019-07-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufactures', '0003_auto_20190727_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='state',
            field=models.CharField(choices=[('para_preparar', 'Para preparar'), ('cortados', 'Cortados'), ('en_costura', 'En costura')], default='para_preparar', max_length=50),
        ),
    ]
