# Generated by Django 2.2.3 on 2019-07-28 21:15

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Manufactures', '0004_auto_20190727_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacture',
            name='state',
        ),
        migrations.RemoveField(
            model_name='manufacture',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='manufacture',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='para_preparar', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='manufacture',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
    ]
