# Generated by Django 3.0.7 on 2020-06-18 22:13

from django.db import migrations
import model_utils.fields


def change_manufactures_status(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Manufacture = apps.get_model("Manufactures", "Manufacture")
    Manufacture.repository.filter(status='para_preparar').update(status='cortados')


class Migration(migrations.Migration):

    dependencies = [
        ('Manufactures', '0005_auto_20190728_1815'),
    ]

    operations = [
        migrations.RunPython(change_manufactures_status),
        migrations.AlterField(
            model_name='manufacture',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='cortados', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
