# Generated by Django 3.0.7 on 2021-01-26 18:18

from django.db import migrations


def change_manufactures_status(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Manufacture = apps.get_model("Manufactures", "Manufacture")
    Manufacture.repository.update(status='en_costura')


class Migration(migrations.Migration):

    dependencies = [
        ('Manufactures', '0006_auto_20200618_1913'),
    ]

    operations = [
        migrations.RunPython(change_manufactures_status),
    ]

