# Generated by Django 2.2.3 on 2019-07-20 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0002_auto_20190720_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.ProductColor')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.ProductSize')),
            ],
        ),
    ]
