# Generated by Django 2.2.3 on 2019-07-27 20:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stock',
            managers=[
                ('repository', django.db.models.manager.Manager()),
            ],
        ),
    ]
