# Generated by Django 2.2.3 on 2020-06-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercadoLibre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meliuser',
            name='app_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='meliuser',
            name='client_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='meliuser',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
