# Generated by Django 2.2.3 on 2020-06-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercadoLibre', '0002_auto_20200614_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meliuser',
            name='token_updated',
        ),
        migrations.AddField(
            model_name='meliuser',
            name='user_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
