# Generated by Django 2.2.3 on 2020-06-14 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20190720_2016'),
        ('MercadoLibre', '0006_meliitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeliItemMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.ProductColor')),
                ('meli_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MercadoLibre.MeliItem')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.ProductSize')),
            ],
        ),
    ]
