# Generated by Django 3.0.7 on 2020-06-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('type', models.CharField(choices=[('venta', 'Venta'), ('retiro', 'Retiro')], max_length=255)),
            ],
        ),
    ]
