# Generated by Django 3.0.7 on 2020-06-19 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_auto_20200618_2146'),
    ]

    operations = [
    ]
