# Generated by Django 3.0.7 on 2020-06-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_auto_20200618_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='type',
            field=models.CharField(choices=[('1', 'Prendas Correo'), ('2', 'Prendas Malabia'), ('3', 'Banco Luli'), ('4', 'Semana Luli'), ('5', 'Banco Dylan'), ('6', 'Semana Dylan')], max_length=255),
        ),
    ]
