# Generated by Django 3.0.7 on 2021-01-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_auto_20200623_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='type',
            field=models.CharField(choices=[('1', 'Prendas Correo'), ('2', 'Facturas Ventas'), ('3', 'Facturas Compras'), ('4', 'Liquidación Laura'), ('5', 'Liquidación Graciela'), ('6', 'Publicidad'), ('7', 'Gastos'), ('8', 'Impuestos')], max_length=255),
        ),
    ]
