# Generated by Django 2.2.3 on 2019-07-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name': 'color', 'verbose_name_plural': 'colores'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': 'talle', 'verbose_name_plural': 'talles'},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(max_length=200, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(max_length=200, verbose_name='talle'),
        ),
    ]
